version: "3.9"

services:
  web:
    build: ..
    command: bash -c "uvicorn internal.cmd:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - db

  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  db:
    container_name:
      postgres_database

    image: postgres:15

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=posts_db

    ports:
      - "5432:5432"




